# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'BaiSiBuDeJie' do

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'MJRefresh'
    
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaiSiBuDeJie

  target 'BaiSiBuDeJieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaiSiBuDeJieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
